prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}

grafana:
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
