apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: liveness-api
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: liveness-chart
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
