replicaCount: 2

image:
  repository: asia-southeast1-docker.pkg.dev/PROJECT/liveness-repo/liveness-api
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1500m"
    memory: "2Gi"

config:
  path: /app/config/config.yaml

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
